### ISSUE TITLE
Large Numbers for Minting Multiple NFTs

### ISSUE THREAD

**Issue by pivxftw** [SecretChainGirl-Foundation/stashh-nft-marketplace#106]
Tested in (Chrome, Safari, Edge, Firefox, etc.): 

## Steps to reproduce
1. Go to 'Mint Multiple NFTs'

## Issue:
I do not know if there is a max limit to number of NFTs under "Amount of Copies".  It doesn't say anywhere, and when I put in a really large number, it wouldn't mint.  Not sure if it was because of this large number

## Expected:
Clear description on the max number of copies that can be made, with field validation

**Comment by scarylooking** [comment]
✨fixed
