### ISSUE TITLE
Marketplace: selected a collection

### ISSUE THREAD

**Issue by jhobsz** [SecretChainGirl-Foundation/stashh-nft-marketplace#130]
After I selected a collection (deserts), the screen showed the NFT, but also was in this display loop of, well, what seems like it's retrieving other collections. It's like in a perpetual refresh.
![Stashh](https://user-images.githubusercontent.com/39382903/141406343-75196fe7-3b01-408e-b937-c1e79fc8393c.jpg)

**Comment by jhobsz** [comment]
Once I chose another collection, I didn't see the refresh. Went back to the deserts collection, didn't see the refresh, but I did see other NFTs that don't seem to be related to Deserts.

**Comment by scarylooking** [comment]
I can't replicate this, but it looks like the site was loading data over a slow connection. The "wipe" animation you're seeing is a loading placeholder. I don't think this is a bug, but if it happens again on the new site after the updated and fixes are complete please re-open this defect
