### ISSUE TITLE
sSCRT conversion screen doesn't show SCRT balance

### ISSUE THREAD

**Issue by AustinWoetzel** [SecretChainGirl-Foundation/stashh-nft-marketplace#15]
![image](https://user-images.githubusercontent.com/30289932/136306852-e177fd8d-cb78-4368-a91a-70542039f5e4.png)

Without showing your SCRT balance on this screen, you don't know how much you have to convert and if you leaving any leftover for gas. You have to jump back to the main screen and check your wallet view in order to verify you are converting the right amount.

**Comment by LourencoMaltez** [comment]
fixed, will be live on the next update!

**Comment by lauraweindorf** [comment]
Verified fix 🎉
