### ISSUE TITLE
Fix Transactions and Sales messages when there are none

### ISSUE THREAD

**Issue by lauraweindorf** [SecretChainGirl-Foundation/stashh-nft-marketplace#16]
Change to "There are no ..."

![image](https://user-images.githubusercontent.com/436905/136439954-3413437a-aaba-4f8b-8ffd-acb6c9a09013.png)

and

![image](https://user-images.githubusercontent.com/436905/136439991-92ff4576-4727-4261-bcfa-99e79925f9f3.png)

**Comment by scarylooking** [comment]
✨fixed
