### ISSUE TITLE
Social icons at the bottom of Wallet menu don't work

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-nft-marketplace#27]
Precondition: add at least 1 social link to your profile with a valid URL

1. Click the wallet button in the top right of the screen
2. The Wallet Menu drops out and shows up to 4 social links at the bottom
3. Click any of the social links
4. Nothing happens

![image](https://user-images.githubusercontent.com/16178367/136465165-b70f189a-f767-40bc-92c3-fb8b937db496.png)

Expected something to happen, however it is odd that it shows my own social links back to me, and it is also odd that it only shows the first 4. I would have expected those links to go to the Secret NFT owned Socials

**Comment by lauraweindorf** [comment]
great job @scarylooking! 

Can you clarify what you mean by "I would have expected those links to go to the Secret NFT owned Socials"?

That's interesting that it showed only the 1st 4 for you. I created a profile that had every possible social link and they all appear for me.

![image](https://user-images.githubusercontent.com/436905/136466810-9c11250b-831c-4bfb-9407-75a63811098d.png)
