### ISSUE TITLE
Collection website is prepending "www." to the URL

### ISSUE THREAD

**Issue by lauraweindorf** [SecretChainGirl-Foundation/stashh-nft-marketplace#34]
Pre-condition: Collection created with website link specified

1. Go to user's Collections page
2. Choose a Collection
3. Click on website link

![image](https://user-images.githubusercontent.com/436905/136585145-ff527197-8a90-436a-ba3b-93e061eecdeb.png)

The field was entered as "https://scrt.network" (per the placeholder format, but when clicked went to "www.https://scrt.network".

![image](https://user-images.githubusercontent.com/436905/136584997-b2b6e40d-cb0d-46b6-8aa6-9b27828c66d1.png)

![image](https://user-images.githubusercontent.com/436905/136584966-cf072087-55cd-416d-b968-81047f86313b.png)

**Comment by scarylooking** [comment]
Resolved on both current and refreshed design
