### ISSUE TITLE
Marketplace is showing NFT that's not on sale

### ISSUE THREAD

**Issue by lauraweindorf** [SecretChainGirl-Foundation/stashh-nft-marketplace#45]
Tested in Chrome.

## Steps to reproduce
1. Purchase an NFT
2. Go to Marketplace, filter on "Buy Now"
3. Recently purchased NFT is displayed as "On Sale"

## Issue:
The NFT was purchased, but I didn't choose to list it. 

## Expected:
NFTs that aren't for sale should not be listed in the Marketplace with the "Buy Now" filter.

![image](https://user-images.githubusercontent.com/436905/137027201-b68490b2-cdf3-4877-9f38-86b526bbd43e.png)

## Note(s):
n/a

**Comment by scarylooking** [comment]
I couldn't replicate this on the refreshed design.

## Test Steps To Close

1. Clicked Marketplace, checked Buy Now was applied, set a Max 1USD filter
2. Bought an NFT from the results
3. Clicked View Profile when transaction confirmed
4. Clicked Marketplace, checked Buy Now was applied, set a Max 1USD filter
5. Checked that NFT was not present in results
