### ISSUE TITLE
SecretChain Girl Foundation Typo

### ISSUE THREAD

**Issue by pivxftw** [SecretChainGirl-Foundation/stashh-nft-marketplace#52]
Tested in (Chrome, Safari, Edge, Firefox, etc.): Chrome

## Steps to reproduce
1. Go to 'Landing Page'

## Issue:
Made with ❤️   by  SecretChian Girl Foundation... SecretChain is spelled wrong

## Expected:
Should be: Made with ❤️   by  SecretChain Girl Foundation

**Comment by scarylooking** [comment]
Resolved in refreshed design
