### ISSUE TITLE
Hidden collection, cancel from the sale is causing 404 page error

### ISSUE THREAD

**Issue by Kenaard** [SecretChainGirl-Foundation/stashh-nft-marketplace#73]
![image](https://user-images.githubusercontent.com/38940654/137705101-bf6e34cb-6294-462d-9224-e7e712e0de1d.png)

![image](https://user-images.githubusercontent.com/38940654/137705131-7321971c-34c6-4d68-be4d-73f8babfd3a1.png)

Steps to reproduce:
1. Create a hidden collection
2. Create nft and put it for sale
3. Cancel nft from sale

Result:
404 error

**Comment by scarylooking** [comment]
Squashed this issue into #78
