### ISSUE TITLE
Asset page in a hidden collection 404s when updating

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-nft-marketplace#78]
Tested in (Chrome, Safari, Edge, Firefox, etc.): Brave

## Steps to reproduce
1. Create a hidden collection
2. Create an NFT within that collection
3. Navigate to the Asset page for the NFT you just created

## Issue:
Any action that causes the page state to reload results in the user being shown a 404 error...

1. Clicking the "refresh from network" button in the top right
2. Updating royalties
3. Listing an NFT for sale
4. Unlisting an NFT for sale

![image](https://user-images.githubusercontent.com/16178367/137972648-ec7c7e70-dd60-40e3-94c2-451a8bf4971d.png)

## Expected:
User should be shown the Asset page with updated values

## Note(s):

If you click the refresh button on the browser or copy the URL into a new tab the asset page loads but with spinners/placeholders forever

![image](https://user-images.githubusercontent.com/16178367/137973234-788d2d10-07cc-46fc-85f7-e6a52005b7a9.png)

If you access the Asset page via the collection the URL is the same, but everything works.

Credit to @Kenaard for spotting this

**Comment by LourencoMaltez** [comment]
Fixed, @scarylooking
