### ISSUE TITLE
Missing record in Minted section

### ISSUE THREAD

**Issue by Kenaard** [SecretChainGirl-Foundation/stashh-nft-marketplace#9]
There is nothing in the minted tab, but there is in owned tab (I minted the piece)

![image](https://user-images.githubusercontent.com/38940654/136259338-e09261fd-a903-451a-a033-ad8b44320b52.png)

![image](https://user-images.githubusercontent.com/38940654/136259420-fb0e3951-f512-4e09-8a33-d2de2574e2ac.png)

**Comment by LourencoMaltez** [comment]
fixed, will be live on the next update

**Comment by lauraweindorf** [comment]
Fix verified 🎉
